sudo: false
dist: trusty
language: node_js

cache:
  directories:
    - node_modules

addons:
  chrome: stable

node_js:
  - "10"

matrix:
  fast_finish: true

before_install:
  - npm install npm@6.4.1 -g
  - npm cache verify
  - npm prune
  - npm update

install:
  - npm install

script:
  - ng test --watch false -cc
  - npm run e2e

 
